### ISSUE TITLE
请问您kdd数据集的wekahead文件是怎样生成的

### ISSUE THREAD

**Issue by Ki-li** [zhanglbjames/kdd#1]
在public void addHeadInfo(BufferedWriter OutFileBw) throws Exception这个函数中是要将数据集的头文件添加到输出的文件中，而我只有kdd原本的数据集，转换为csv文件后手动添加一行属性值可以识别吗？

**Comment by Ki-li** [comment]
我在把数据保存为csv后添加了一行属性，用weka另存为arff文件获得了头文件信息，但是在运行时还是报错不能识别为arff文件，而且在kdd99_roughset_test.tab文件写完后在所有原有的属性值后面都加了normal，请问我的数据集制备有错误吗？
Exception in thread "main" java.io.IOException: Unable to determine structure as arff (Reason: java.io.IOException: } expected at end of enumeration, read Token[EOL], line 7).
	at weka.core.converters.ArffLoader.getStructure(ArffLoader.java:1251)
	at weka.core.converters.ArffLoader.getDataSet(ArffLoader.java:1280)
	at rseslib.structure.data.formats.ArffDoubleDataInput.<init>(ArffDoubleDataInput.java:70)
	at rseslib.structure.table.ArrayListDoubleDataTable.<init>(ArrayListDoubleDataTable.java:87)
	at kdd99.roughset.RoughSet.<init>(RoughSet.java:71)
	at kdd99.complete.RoughSetComplete.classiftyTest(RoughSetComplete.java:56)
	at kdd99.complete.RoughSetComplete.main(RoughSetComplete.java:61)
